apiVersion: batch/v1
kind: Job
metadata:
  name: okra-load-queue
spec:
  parallelism: 1
  template:
    metadata:
      name: okra
    spec:
      nodeSelector:
        master: "queue"
      containers:
      - name: c
        image: gcr.io/school-232423/okra
        command: ["okra"]
        args: ["--redis", "job2", "--load_redis","repo_list/repos_assn1"]
        volumeMounts:
          - name: scrt
            mountPath: "/etc/scrt"
          - name: cache-volume
            mountPath: "/cache"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/etc/scrt/tbonza-gcloud-storage.json"
          - name: REDIS_SERVICE_HOST
            value: "redis-master"
          - name: BUCKET_ID
            value: "ds6050"
          - name: CACHE
            value: "/cache/"
      volumes:
        - name: scrt
          secret:
            secretName: tbonza-gcloud-storage
        - name: cache-volume
          emptyDir: {}
      restartPolicy: OnFailure
