# (generated with --quick)

from typing import Any

hashlib: module
redis: module
uuid: module

class RedisWQ(object):
    __doc__: str
    _db: Any
    _lease_key_prefix: Any
    _main_q_key: Any
    _processing_q_key: Any
    _session: str
    def __init__(self, name, **redis_kwargs) -> None: ...
    def _itemkey(self, item) -> str: ...
    def _lease_exists(self, item) -> Any: ...
    def _main_qsize(self) -> Any: ...
    def _processing_qsize(self) -> Any: ...
    def complete(self, value) -> None: ...
    def empty(self) -> Any: ...
    def lease(self, lease_secs = ..., block = ..., timeout = ...) -> Any: ...
    def sessionID(self) -> str: ...
