- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
        keypair: "aws_key"
        group: whatever
        instance_type: t2.nano
        region: "{{ ec2_region }}"
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        instance_tags:
          Name: Build
        count_tag:
          Name: Build

