---
- hosts: ec2
  name: configuration play
  remote_user: ec2-user
  gather_facts: true

  tasks:

    - name: u up?
      ping:

    - name: docker
      become: yes
      yum:
        name: docker
        state: latest

    - name: git
      become: yes
      yum:
        name: git
        state: latest

    - name: emacs
      become: yes
      yum:
        name: emacs
        state: latest

