---
- hosts: ec2
  name: configuration play
  remote_user: ubuntu
  gather_facts: false

  tasks:

    - name: u up?
      ping:

    - name: check updates
      become: yes
      apt:
        upgrade: dist

    - name: git
      become: yes
      apt:
        name: git
        state: latest

    - name: Add Docker GPG key
      become: yes
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      become: yes
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
        state: present
        update_cache: yes

    - name: Install kubectl
      become: yes
      command: snap install kubectl --classic

    - name: Install minikube
      become: yes
      copy:
        src: files/minikube
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0555

    - name: start docker
      become: yes
      command: systemctl start docker
