---
- hosts: ec2
  name: configuration play
  remote_user: ec2-user
  gather_facts: true

  tasks:

    - name: u up?
      ping:

    - name: Update packages
      become: yes
      yum:
        name: '*'
        state: latest

    - name: docker
      become: yes
      yum:
        name: docker
        state: latest

    - name: git
      become: yes
      yum:
        name: git
        state: latest

    - name: emacs
      become: yes
      yum:
        name: emacs
        state: latest

    - name: kubectl repo
      become: yes
      copy:
        src: files/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
        owner: root
        group: root
        mode: 0644

    - name: kubectl
      become: yes
      yum:
        name: kubectl
        state: latest

    - name: systemd
      become: yes
      yum:
        name: systemd
        state: latest
