- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Create key pair
      ec2_key:

        name: ds6050
        region: "{{ ec2_region }}"
        state: present

    - name: Provision a set of instances
      ec2:
        
        key_name: ds6050
        instance_type: t2.nano
        region: "{{ ec2_region }}"
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2
          
